#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh

# Use a fixed sort order.
export LC_ALL=C
sudo -S dpkg -l | awk '/^ii/ {print $2}' | cut -f1 -d: | sort -u > env/debian/pkgo.txt
comm -13 --check-order env/debian/pkgo.txt env/debian/pkgs.txt
rm env/debian/pkgo.txt
