#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh

APTARGS=${APTARGS:---no-remove}

pkgs="$($BASE/check)"
[ -z "$pkgs" ] && exit

sudo -S DEBIAN_FRONTEND=noninteractive apt-get install $APTARGS --no-install-recommends $pkgs
